### PR TITLE
(feat)Fetches quotes every twelve minutes if you have a cron job to do it

### PR DESCRIPTION
**Pull request by jsoo1**
Don't add one though cause we only get 10 quotes/hour

### CODE REVIEW

**Comment by mfrazie2** [comment]
Where are the quotes going on the app? I'm not seeing a component that renders the quote data.

**Comment by jsoo1** [comment]
Chris is working on the front-end now

**Comment by mfrazie2** [comment]
Sounds good. 

Is there anything we have to do on our personal forks to get the quotes? You mention not adding the cron job above. Will the functionality break if the component is not receiving updated quotes?

**Comment by jsoo1** [comment]
Good point. I'll add a default value

**Comment by jsoo1** [comment]
This adds a default value. Should be good now

**Pull request merged**
